version: '3.8'
services:
  edunex-api:
    image: mostafasalem2/edunex-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5293"
    environment:
      DB_HOST: 
      DB_NAME: 
      DB_USER: 
      DB_PASSWORD: 
    restart: 
