name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker Image"]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image from Docker Hub
        run: sudo docker pull mostafasalem2/edunex-api:latest
      - name: Stop and remove old container if it exists
        run: sudo docker rm -f edunex-api-container || true
      - name: Run Docker container
        run: sudo docker run -d -p 8080:8080 --name edunex-api-container mostafasalem2/edunex-api:latest



